services:
  stremio-profiles:
    build: .
    container_name: stremio-profiles
    restart: unless-stopped
    ports:
      - "0.0.0.0:7000:7000"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=7000
      - BASE_URL=${BASE_URL:-http://158.180.57.245:7000}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - DB_PATH=/app/data/profiles.db
